name: 'sn-check-object-status'
description: 'Github Action to wait for an object to reach a given status on ServiceNow.'
author: 'dannevesdantas'
branding:
  color: purple
  icon: clock
inputs:
  server:
    description: 'ServiceNow instance URL'
    required: true
  username:
    description: 'ServiceNow username'
    required: false
  password:
    description: 'ServiceNow password'
    required: false
  table_name:
    description: 'Supply the technical table name in which to search.'
    required: true
  sys_id:
    description: 'The technical id of the task.'
    required: true
  polling_interval:
    description: 'Polling interval in seconds.'
    required: true
  status_field:
    description: 'The technical name of a field to check.'
    required: true
  status_to_check_for:
    description: 'The display value to look for in the field.'
    required: true
  finished_status:
    description: 'If status is this value, consider this done'
    required: false
  aborted_status:
    description: 'If status is this value, consider this aborted'
    required: false
  timeout:
    description: 'Maximum time in seconds before timing out. ( 0 = never times out)'
    required: false
  skip_on_timeout:
    description: 'Skip this gate if waiting times out'
    required: false
  
runs:
  using: 'node12'
  main: 'index.js'
