name: 'ssn-wait-change-approval'
description: 'Github Action to wait for a change request to be approved on ServiceNow.'
author: 'dannevesdantas'
branding:
  color: purple
  icon: clock
inputs:
  server:
    description: 'ServiceNow instance URL'
    required: true
  username:
    description: 'ServiceNow username'
    required: false
  password:
    description: 'ServiceNow password'
    required: false
  sys_id:
    description: 'Change Unique record identifier'
    required: true
  interval:
    description: 'Interval between approval verifications in minutes'
    required: false
    default: 5
runs:
  using: 'node12'
  main: 'index.js'
